meta:
  environment: safe-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: vault
    networks:
      - name: safe
        static_ips: (( static_ips 0 1 2 ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small
    cloud_properties:
      name: random

networks:
- name: safe
  type: manual
  subnets:
  - range: 10.244.4.0/24
    name: safe1
    gateway: 10.244.4.1
    static:
      - 10.244.4.2 - 10.244.4.60
