meta:
  environment: ~

jobs:
  - name: vault
    templates:
      - { release: safe, name: vault }
    instances: 3
    resource_pool: small
    networks: (( param "please set safe networks" ))

networks: (( param "please set networks" ))

properties:
  safe:
    cluster_ips: (( grab jobs.vault.networks.safe.static_ips ))
    peer:
      tls:
        verify: false
